[workspace]
members = ["crates/op-test-vectors", "crates/opt8n"]
resolver = "2"

[workspace.package]
version = "0.0.1"
authors = ["Eric Woolsey<ewoolsey@ualberta.ca>"]
edition = "2021"
license = "MIT"
repository = "https://github.com/ethereum-optimism/op-test-vectors"
homepage = "https://github.com/ethereum-optimism/op-test-vectors"
exclude = ["**/target", "benches/", "tests"]

[workspace.dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "1"
color-eyre = "0.6"
lazy_static = "1"
tracing = "0.1"
tokio = { version = "1", features = ["full"] }
futures = "0.3"
clap = { version = "4", features = ["derive"] }
shellwords = "1"

# Eth
op-alloy-rpc-types = "0.1.2"
op-alloy-consensus = "0.1.2"
alloy = { version = "0.1.4", features = ["rpc", "rpc-types-trace"] }
anvil = { git = "https://github.com/foundry-rs/foundry", default-features = true, rev = "7c4482fc9541f11b57575e2d8bf7bd190b61bda6" }
anvil-core = { git = "https://github.com/foundry-rs/foundry", default-features = true, rev = "7c4482fc9541f11b57575e2d8bf7bd190b61bda6" }
cast = { git = "https://github.com/foundry-rs/foundry", rev = "7c4482fc9541f11b57575e2d8bf7bd190b61bda6" }
forge-script = { git = "https://github.com/foundry-rs/foundry", rev = "7c4482fc9541f11b57575e2d8bf7bd190b61bda6" }

revm = { version = "10.0.0", default-features = false, features = ["alloydb"]}
revm-primitives = { version = "5.0.0", default-features = false }
revm-inspectors = { version = "0.3", features = ["serde"] }

# Internal
op-test-vectors = { path = "crates/op-test-vectors" }
