[workspace]
members = ["crates/*", "bin/opt8n", "bin/opd8n"]
default-members = ["bin/opt8n", "bin/opd8n"]
resolver = "2"

[workspace.package]
edition = "2021"
license = "MIT"
authors = ["Eric Woolsey<ewoolsey@ualberta.ca>", "refcell"]
repository = "https://github.com/ethereum-optimism/op-test-vectors"
homepage = "https://github.com/ethereum-optimism/op-test-vectors"
exclude = ["**/target", "benches/", "tests"]

[workspace.dependencies]
# General
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "1"
color-eyre = "0.6"
lazy_static = "1"
tracing = "0.1"
tokio = { version = "1", features = ["full"] }
futures = "0.3"
clap = { version = "4", features = ["derive"] }
shellwords = "1"

# Eth
op-alloy-rpc-types = "0.1.2"
op-alloy-consensus = "0.1.2"
alloy = { version = "0.1.4", features = [
    "rpc",
    "rpc-types-trace",
    "consensus",
    "providers"
] }
foundry-common = { git = "https://github.com/foundry-rs/foundry", default-features = true, rev = "7c4482fc9541f11b57575e2d8bf7bd190b61bda6" }
anvil = { git = "https://github.com/foundry-rs/foundry", default-features = true, rev = "7c4482fc9541f11b57575e2d8bf7bd190b61bda6" }
anvil-core = { git = "https://github.com/foundry-rs/foundry", default-features = true, rev = "7c4482fc9541f11b57575e2d8bf7bd190b61bda6" }
cast = { git = "https://github.com/foundry-rs/foundry", rev = "7c4482fc9541f11b57575e2d8bf7bd190b61bda6" }
forge-script = { git = "https://github.com/foundry-rs/foundry", rev = "7c4482fc9541f11b57575e2d8bf7bd190b61bda6" }
revm = { version = "10.0.0", features = ["alloydb", "optimism"] }
revm-inspectors = { version = "0.3", features = ["serde"] }

# Internal
op-test-vectors = { path = "crates/op-test-vectors" }
