[package]
name = "opt8n"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
publish = false

[dependencies]
# Workspace
alloy.workspace = true
op-test-vectors.workspace = true
clap.workspace = true
shellwords.workspace = true
tokio.workspace = true
futures.workspace = true
color-eyre.workspace = true
foundry-common.workspace = true
anvil.workspace = true
anvil-core.workspace = true
cast.workspace = true
forge-script.workspace = true
revm.workspace = true
revm-inspectors.workspace = true
op-alloy-rpc-types.workspace = true

# External
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }
tracing = { version = "0.1" }
