[package]
name = "opt8n"
version = "0.2.0"
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
publish = false

[dependencies]
# Core
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true
tokio.workspace = true
futures.workspace = true
color-eyre.workspace = true
axum.workspace = true

# CLI
clap.workspace = true
shellwords.workspace = true

# Alloy
alloy-eips.workspace = true
alloy-rpc-types.workspace = true

# Foundry
foundry-common.workspace = true
anvil.workspace = true
anvil-core.workspace = true
cast.workspace = true
forge-script.workspace = true
revm.workspace = true

# OP Types
op-test-vectors.workspace = true
op-alloy-rpc-types.workspace = true
